name: CI

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.x
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate prisma client
        working-directory: apps/api
        run: pnpm prisma generate

      - name: Generate types package
        working-directory: packages/types
        run: pnpm build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm and Node.js
        uses: pnpm/action-setup@v3
        with:
          version: 10.x
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - name: Generate prisma client
        working-directory: apps/api
        run: pnpm prisma generate

      - name: Generate types package
        working-directory: packages/types
        run: pnpm build

      - name: Run all tests
        run: pnpm test
