name: Lint & format

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.x
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate prisma
        working-directory: apps/api
        run: pnpm prisma generate

      - name: Generate types package
        working-directory: packages/types
        run: pnpm build

      - name: Run ESlint
        run: pnpm lint

      - name: Check formatting
        run: pnpm format:check
